CREATE TABLE IF NOT EXISTS USERS
(
    ID             SERIAL PRIMARY KEY,
    USERNAME       VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS SEGMENTS
(
    ID     SERIAL PRIMARY KEY,
    NAME   VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USER_SEGMENTS
(
    ID             SERIAL PRIMARY KEY,
    USER_ID        INTEGER,
    SEGMENT_ID     INTEGER,
    CREATED        TIMESTAMP NOT NULL,
    EXPIRED        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HISTORY
(
    ID             SERIAL PRIMARY KEY,
    USER_ID        INTEGER NOT NULL,
    SEGMENT_ID     INTEGER NOT NULL,
    OPERATION      VARCHAR(255) NOT NULL,
    DATE           TIMESTAMP NOT NULL
);

ALTER TABLE USER_SEGMENTS
    ADD CONSTRAINT USER_SEGMENTS_SEGMENTS_ID_FK
        FOREIGN KEY (SEGMENT_ID) REFERENCES SEGMENTS;

ALTER TABLE USER_SEGMENTS
    ADD CONSTRAINT USER_SEGMENTS_USERS_ID_FK
        FOREIGN KEY (USER_ID) REFERENCES USERS;

ALTER TABLE USER_SEGMENTS
    ADD CONSTRAINT CONSTRAINT_NAME UNIQUE (USER_ID, SEGMENT_ID);